### ISSUE TITLE
Support fullscreening apps

### ISSUE THREAD

**Issue by cmsj** [sdegutis/mjolnir#160]
Hi

It'd be great if I could bind a hotkey to toggle fullscreen for apps that support it.

Cheers,

Chris

**Comment by sdegutis** [comment]
:+1:

**Comment by sdegutis** [comment]
We can make an app full screen (in Mavericks at least) by finding the element of a window with the subrole `AXFullScreenButton` and pressing it, which is almost the exact same way that we do `window:close()`. But once it's full screen, un-fullscreen-izing it is harder, since the button is no longer the same one. These are its details, found using the UIElementInspector sample project from Mac OS X 10.2's documentation (wow, that's old):

```
<AXApplication: “Xcode”>
 <AXMenuBar>
  <AXMenuBarItem: “”>

Attributes:
   AXEnabled:  “1”
   AXDescription:  “(null)”
   AXParent:  “<AXMenuBar>”
   AXSize:  “w=38 h=22”
   AXFocused:  “0”
   AXChildren:  “(null)”
   AXRole:  “AXMenuBarItem”
   AXTopLevelUIElement:  “(null)”
   AXHelp:  “(null)”
   AXPosition:  “x=2522 y=0”
   AXTitle:  “”
   AXValue:  “1”
   AXRoleDescription:  “menu bar item”
   AXSelected:  “0”
   AXWindow:  “(null)”

Actions:
   AXPress - press
   AXCancel - cancel
```

**Comment by sdegutis** [comment]
For reference, the "exit full screen mode" button in the menu bar is nearly identical to any regular `NSStatusItem`. Here's what [Bahamut](https://github.com/sdegutis/bahamut)'s NSStatusItem looks like:

```
<AXApplication: “Bahamut”>
 <AXMenuBar>
  <AXMenuBarItem: “”>

Attributes:
   AXEnabled:  “1”
   AXDescription:  “(null)”
   AXParent:  “<AXMenuBar>”
   AXSize:  “w=315 h=22”
   AXFocused:  “0”
   AXChildren:  “(null)”
   AXRole:  “AXMenuBarItem”
   AXTopLevelUIElement:  “(null)”
   AXHelp:  “(null)”
   AXPosition:  “x=1902 y=0”
   AXTitle:  “”
   AXWindow:  “(null)”
   AXRoleDescription:  “menu bar item”
   AXSelected:  “0”

Actions:
   AXPress - press
   AXCancel - cancel
```
